const workProjects = [
  {
    id: 1,
    src: "/projects/aasaan/tile.png",
    hoverSrc: "/projects/aasaan/hover.gif",
    col: "col-span-1",
    row: "row-span-2",
    className: "!w-full !h-full",
    title: "AASAAN",
    description: [
      "Brand Strategy",
      "Product Feature Design",
      "Product Enhancement",
    ],
    subtitle:
      "Construction Management Platform | Digital Transformation Consulting",
  },
  {
    id: 2,
    src: "/projects/waste-to-energy/tile.png",
    hoverSrc: "/projects/aasaan/hover.gif",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full",
    title: "WASTE TO ENERGY",
    description: [
      "Management Consulting",
      "Design & master planning",
      "Project Execution",
    ],
    subtitle: "Clean India Mission | Energy Transition",
  },
  {
    id: 3,
    src: "/projects/stackbuilder/tile.png",
    hoverSrc: "/projects/stackbuilder/hover.gif",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full",
    title: "STACKBUILDER",
    description: ["Website Design", "Branding", "UX Lead"],
    subtitle: "Content & Marketing | Creative Consulting",
  },
  {
    id: 4,
    src: "/projects/eusotrip/tile.png",
    hoverSrc: "/projects/eusotrip/hover.gif",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full",
    title: "EUSOTRIP",
    description: [
      "Visual Identity",
      "Investor Pitch",
      "UI Flow",
      "Prototype Design",
    ],
    subtitle:
      "HazMat Logistics | Digital Platform | B2B industrial logistics solution",
  },
  {
    id: 5,
    src: "/projects/gcapita/tile.png",
    hoverSrc: "/projects/gcapita/hover.gif",
    col: "col-span-1",
    row: "row-span-2",
    className: "!w-full !h-full",
    title: "G CAPITAL",
    description: ["Product Identity", "Business Analysis", "Product Prototype", "Dashboard Design"],
    subtitle: "Investment Platform | Crypto-Commodities-Stocks",
  },
  {
    id: 6,
    src: "/projects/spendo/tile.png",
    hoverSrc: "/projects/spendo/hover.gif",
    col: "col-span-2",
    row: "row-span-1",
    className: "!w-full !h-full",
    title: "SPENDO",
    description: ["Website Design", "Product UX"],
    subtitle: "Corporate petty cash management solution",
  },
  {
    id: 7,
    src: "/projects/pawsome/tile.gif",
    hoverSrc: "/projects/pawsome/hover.png",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full rounded-xl",
    title: "PAWSOME",
    description: [
      "Product Research",
      "User Experience",
      "Design Mockups",
    ],
    subtitle: "Pet Platform for Connecting | Pet enthusiasts as a community",
  },
  {
    id: 8,
    src: "/projects/construct360/tile.png",
    hoverSrc: "/projects/construct360/hover.gif",
    col: "col-span-2",
    row: "row-span-1",
    className: "!w-full !h-full rounded-xl",
    title: "CONSTRUCT360",
    description: [
      "Dashboard Design",
      "User Experience",
      "Project Collaboration",
    ],
    subtitle: "Business Intelligence | Internal Construction Project Management System",
  },
  {
    id: 9,
    src: "/projects/unesco-chair/tile.png",
    hoverSrc: "/projects/unesco-chair/hover.gif",
    col: "col-span-1",
    row: "row-span-2",
    className: "!w-full !h-full rounded-xl",
    title: "UNESCO CHAIR",
    description: [
      "Proposal",
      "Curating",
      "Content Strategy",
      "Digital Media"
    ],
    subtitle: "Clean India Mission | Energy Transition",
  },
  {
    id: 10,
    src: "/projects/kafzeit/tile.gif",
    hoverSrc: "/projects/kafzeit/hover.gif",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full rounded-xl",
    title: "Kafzeit",
    description: [
      "Market Research",
      "Experience  Design",
      "Brand Consulting",
      "Digital Store",
    ],
    subtitle: "Coffee House in Berlin | Business Consulting",
  },
  {
    id: 11,
    src: "/projects/digital-transformation/tile.png",
    hoverSrc: "/projects/digital-transformation/hover.gif",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full rounded-xl",
    title: "DIGITAL TRANSFORMATION",
    description: [
      "Proposal ",
      "Methodology",
      "Business Development Strategy",
    ],
    subtitle: "Master Thesis | Management Research",
  },
  {
    id: 12,
    src: "/projects/mitmut-studio/tile.png",
    hoverSrc: "/projects/mitmut-studio/hover.gif",
    col: "col-span-2",
    row: "row-span-1",
    className: "!w-full !h-full rounded-xl",
    title: "MITMUT STUDIO",
    description: [
      "Business Model",
      "Investor Pitch",
      "Product Visuals",
    ],
    subtitle: "Pressed Funding for Product Development | Eduverse as Gamified Learning Experience  ",
  },
];

export default workProjects;
